kind: ConfigMap
apiVersion: v1
metadata:
  name: workspace-userdata-gitconfig-configmap
  namespace: rludva-devspaces
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-configmap: 'true'
  annotations:
    controller.devfile.io/mount-as: subpath
    controller.devfile.io/mount-path: /etc/
data:
  gitconfig: |
    [user]
    name = Radomir Ludva
    email = noreplay@radmi.cz
    [credential]
    helper = cache --timeout=2592000
    [push]
    default = matching
    [init]
    defaultBranch = main
